name: verdict
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cppimport==22.8.2
      - cycler==0.12.1
      - dill==0.4.0
      - fairscale==0.4.13
      - filelock==3.18.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - mako==1.3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.2.1
      - psutil==7.0.0
      - pulp==3.2.1
      - pybind11==2.13.6
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - six==1.17.0
      - sympy==1.14.0
      - tiktoken==0.9.0
      - torch==2.4.0
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - z3-solver==4.15.1.0
prefix: /home/azureuser/miniconda3/envs/verdict
